// The following program is generated by Gemini AI on January 21, 2026.

use rustfft::{FftPlanner, num_complex::Complex};
use std::f32::consts::PI;

pub fn fast_fft() {
    let sample_rate = 1000.0;
    let frequency = 50.0;
    let num_samples = 1024;

    let mut buffer: Vec<Complex<f32>> = (0..num_samples)
        .map(|i| {
            let t = i as f32 / sample_rate;
            let amplitude = (2.0 * PI * frequency * t).sin();
            Complex {
                re: amplitude,
                im: 0.0,
            }
        })
        .collect();

    let mut planner = FftPlanner::new();
    let fft = planner.plan_fft_forward(num_samples);

    fft.process(&mut buffer);

    let (peak_index, _max_mag) = buffer
        .iter()
        .take(num_samples / 2)
        .enumerate()
        .map(|(i, c)| (i, c.norm()))
        .max_by(|a, b| a.1.partial_cmp(&b.1).unwrap())
        .unwrap();

    let _found_freq = (peak_index as f32) * sample_rate / (num_samples as f32);
}


